# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc ""
  homepage "https://github.com/pomdtr/arc"
  version "0.2.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pomdtr/arc/releases/download/v0.2.4/arc_0.2.4_darwin_amd64.tar.gz"
    sha256 "c0d07a23abc2429125a487cd8e46a6d9cccca987e42483b634b4804f43dcc64c"

    def install
      bin.install "arc"
      bash_completion.install "completions/arc.bash"
      zsh_completion.install "completions/arc.zsh"
      fish_completion.install "completions/arc.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pomdtr/arc/releases/download/v0.2.4/arc_0.2.4_darwin_arm64.tar.gz"
    sha256 "df459839db3b16abd225b63de4a5a42f30612b506f42134f3efd2aa1c0bb2e7f"

    def install
      bin.install "arc"
      bash_completion.install "completions/arc.bash"
      zsh_completion.install "completions/arc.zsh"
      fish_completion.install "completions/arc.fish"
    end
  end
end
