# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc ""
  homepage "https://github.com/pomdtr/arc"
  version "0.2.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pomdtr/arc/releases/download/v0.2.4/arc_0.2.4_darwin_amd64.tar.gz"
    sha256 "5c10c9ad0a177bc278cdf14a722af9d759ffcfbc2b55dd1196a0c87d08518c79"

    def install
      bin.install "arc"
      bash_completion.install "completions/arc.bash"
      zsh_completion.install "completions/arc.zsh"
      fish_completion.install "completions/arc.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pomdtr/arc/releases/download/v0.2.4/arc_0.2.4_darwin_arm64.tar.gz"
    sha256 "dfece00250d9e3ad7a9692e1a75d830b59623b88307b27d9c68a74b9963f8aad"

    def install
      bin.install "arc"
      bash_completion.install "completions/arc.bash"
      zsh_completion.install "completions/arc.zsh"
      fish_completion.install "completions/arc.fish"
    end
  end
end
