# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc ""
  homepage "https://github.com/pomdtr/ask"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.2/ask-0.1.2-darwin_amd64.tar.gz"
      sha256 "4e01f6bfafad0fd45c29e6847b025d92bf9860286046f85d5ee951b29a559b91"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.2/ask-0.1.2-darwin_arm64.tar.gz"
      sha256 "08ba3cd7778f7454b94f9bea1fc0e9de9ad56632797f0085b2a1de50cdabf140"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.2/ask-0.1.2-linux_arm64.tar.gz"
      sha256 "9ff8f5112cc654698b524f932d9d3ad9ba2cdce2425188b08a7d66707a8a828c"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.2/ask-0.1.2-linux_amd64.tar.gz"
      sha256 "b7a16e6fd49c9cec2359457b453da798ae2e853f9e4873b9fee387769c733cf5"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end
end
