# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc ""
  homepage "https://github.com/pomdtr/ask"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.0/ask-0.1.0-darwin_amd64.tar.gz"
      sha256 "f83e79ac8c3d16ec8dbfe0a24f9179441ca0cae2d672a8970577294520e94320"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.0/ask-0.1.0-darwin_arm64.tar.gz"
      sha256 "6c3ae26c0f5c82e581833e30915c7b772ce18909d53f8abab6b12863d7d45a04"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.0/ask-0.1.0-linux_arm64.tar.gz"
      sha256 "26b06f68c74142f4aebc6775084ba766ba5a2d86f2925a970ce6030a9cbbcf8b"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.0/ask-0.1.0-linux_amd64.tar.gz"
      sha256 "8a17c1a7e1dab6433a0c59b27c0d4f50ace979745fd45b9a155032589e239d2e"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end
end
