# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc ""
  homepage "https://github.com/pomdtr/ask"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.1/ask-0.1.1-darwin_amd64.tar.gz"
      sha256 "aea24fccd0c52b45a8ebfe6be2b2c3012c86e9ed9d340a11b9dc466ee8665b3a"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.1/ask-0.1.1-darwin_arm64.tar.gz"
      sha256 "f04d8faebe74351784697f44fab0f8d5113f0af9e148c91af24ab0a60dbb3454"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.1/ask-0.1.1-linux_amd64.tar.gz"
      sha256 "7c01ee5bb6b3b4a4c6e1e508a674bfa1a9c6c61ee6306c856a3b3e8e91907bc3"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/ask/releases/download/v0.1.1/ask-0.1.1-linux_arm64.tar.gz"
      sha256 "7dc553264e7b43c09ef4e8b6eb52eb91de6f1a75f4deeb722332ee03cc60b618"

      def install
        bin.install "ask"
        bash_completion.install "completions/ask.bash"
        zsh_completion.install "completions/ask.zsh"
        fish_completion.install "completions/ask.fish"
      end
    end
  end
end
