# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Popcorn < Formula
  desc ""
  homepage "https://pomdtr.github.io/popcorn"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/popcorn/releases/download/v0.1.1/popcorn-0.1.1-darwin_amd64.tar.gz"
      sha256 "943b48d975b3eb7472a3fb0695199906f7c82e54b050bc7b5891074af71dc237"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/popcorn/releases/download/v0.1.1/popcorn-0.1.1-darwin_arm64.tar.gz"
      sha256 "567f9be9a49032c60e728d16915ecb63f85d0ea71eba900e3b2b471c9a1e77f3"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/popcorn/releases/download/v0.1.1/popcorn-0.1.1-linux_arm64.tar.gz"
      sha256 "0de95918c5f4cdc1967c9ebf7de78804c1f25472bafe25dbe9d016b475dc4143"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/popcorn/releases/download/v0.1.1/popcorn-0.1.1-linux_amd64.tar.gz"
      sha256 "454e5cb6e944a03551fdff164e8efb3c137c7fb9d4a1b8f836681cc424607b2b"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
  end
end
