# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Popcorn < Formula
  desc ""
  homepage "https://pomdtr.github.io/popcorn"
  version "1.0.0-rc.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/popcorn/releases/download/v1.0.0-rc.7/popcorn-1.0.0-rc.7-darwin_arm64.tar.gz"
      sha256 "1601c664c565b877d9520e8bc57642a98a1311e040761ae1322b2b77cdd85210"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/popcorn/releases/download/v1.0.0-rc.7/popcorn-1.0.0-rc.7-darwin_amd64.tar.gz"
      sha256 "30a0a1d1bfbee7669affc1a8690e90e5075c99ff599b6bb1004e795f317ebb66"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/popcorn/releases/download/v1.0.0-rc.7/popcorn-1.0.0-rc.7-linux_amd64.tar.gz"
      sha256 "b898d5645efbe5fa00ad5d659ab2739c8d6e70916ca80a0ef5a56b2bdebb08f0"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/popcorn/releases/download/v1.0.0-rc.7/popcorn-1.0.0-rc.7-linux_arm64.tar.gz"
      sha256 "c63648644f0d2f8d0829295983a4ab7ecc0fd078b209a60665e81b6440668f8b"

      def install
        bin.install "popcorn"
        bash_completion.install "completions/popcorn.bash"
        zsh_completion.install "completions/popcorn.zsh"
        fish_completion.install "completions/popcorn.fish"
      end
    end
  end
end
