# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ray < Formula
  desc ""
  homepage "https://github.com/pomdtr/ray"
  version "0.1.4"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.4/ray_0.1.4_darwin_amd64.tar.gz"
      sha256 "f9d3b9019076324d77b7800482fa0ea83ff351eb47bb3c459c380ed486b0f303"

      def install
        bin.install "ray"
        # bash_completion.install "completions/ray.bash"
        # zsh_completion.install "completions/ray.zsh"
        # fish_completion.install "completions/ray.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.4/ray_0.1.4_darwin_arm64.tar.gz"
      sha256 "f54beb622a5c0b035e2d9ed5a7a6f69cefe5fef95b1bfd3bb98e30c42d1e172c"

      def install
        bin.install "ray"
        # bash_completion.install "completions/ray.bash"
        # zsh_completion.install "completions/ray.zsh"
        # fish_completion.install "completions/ray.fish"
      end
    end
  end
end
