# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ray < Formula
  desc ""
  homepage "https://github.com/pomdtr/ray"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.3/ray_0.1.3_darwin_arm64.tar.gz"
      sha256 "b46d40a57403486d551e267a2519877db1cbd3108901e30e04e825a37883be9d"

      def install
        bin.install "ray"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.3/ray_0.1.3_darwin_amd64.tar.gz"
      sha256 "802795f982310b63e8681d15677a9a1834ddbe4c20489a3256b9ff685d203627"

      def install
        bin.install "ray"
      end
    end
  end
end
