# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ray < Formula
  desc ""
  homepage "https://github.com/pomdtr/ray"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.3/ray_0.1.3_darwin_amd64.tar.gz"
      sha256 "4ddb503cdb39c8dbe3fb88411ba490c03886d0daee35dd8aeecf94d2aad7b259"

      def install
        bin.install "ray"
        # bash_completion.install "completions/ray.bash"
        # zsh_completion.install "completions/ray.zsh"
        # fish_completion.install "completions/ray.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/ray/releases/download/v0.1.3/ray_0.1.3_darwin_arm64.tar.gz"
      sha256 "47929bda86bbef78f0f9062a98bc4586abb4a2a7a85aa8c301fd7b29fb173621"

      def install
        bin.install "ray"
        # bash_completion.install "completions/ray.bash"
        # zsh_completion.install "completions/ray.zsh"
        # fish_completion.install "completions/ray.fish"
      end
    end
  end
end
