# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raycast < Formula
  desc ""
  homepage "https://github.com/pomdtr/raycast-cli"
  version "0.1.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/raycast-cli/releases/download/v0.1.0/raycast-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "c8f68b95bda1400f75b7fcad0d205376baf9df209b3c04084e939e3b44a874c5"

      def install
        bin.install "raycast"
        bash_completion.install "completions/raycast.bash"
        zsh_completion.install "completions/raycast.zsh"
        fish_completion.install "completions/raycast.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/raycast-cli/releases/download/v0.1.0/raycast-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "646fe4ddf41e076793d842bb37a96b8a79b88a72c807020d291b923b509379a0"

      def install
        bin.install "raycast"
        bash_completion.install "completions/raycast.bash"
        zsh_completion.install "completions/raycast.zsh"
        fish_completion.install "completions/raycast.fish"
      end
    end
  end
end
