# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smallweb < Formula
  desc ""
  homepage "https://smallweb.run"
  version "0.25.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.25.1/smallweb_Darwin_x86_64.tar.gz"
      sha256 "701db9a2adc31c6599c60fe6e130afd3f97478dc30322b35e2f6ff1993a5f230"

      def install
        bin.install "smallweb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.25.1/smallweb_Darwin_arm64.tar.gz"
      sha256 "595a2c13de012cb928efa3de1532c30cd5196ba3e6ad776b6aeb0f101e94f93e"

      def install
        bin.install "smallweb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pomdtr/smallweb/releases/download/v0.25.1/smallweb_Linux_x86_64.tar.gz"
        sha256 "ce81b459a1023b152e84741f80b5807acfa159d01ec9486e497daa1278a208ab"

        def install
          bin.install "smallweb"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pomdtr/smallweb/releases/download/v0.25.1/smallweb_Linux_arm64.tar.gz"
        sha256 "f216c04b0fabdd291791a7699373659f7026b523ae789c8786e629e6477beb99"

        def install
          bin.install "smallweb"
        end
      end
    end
  end

  service do
    run [ opt_bin/"smallweb" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/smallweb.log"
    error_log_path var/"log/smallweb.log"
  end
end
