# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smallweb < Formula
  desc ""
  homepage "https://smallweb.run"
  version "0.13.1"

  on_macos do
    on_intel do
      url "https://github.com/pomdtr/smallweb/releases/download/v0.13.1/smallweb_Darwin_x86_64.tar.gz"
      sha256 "44f68e01a895486de225dbbb3136b9a34d7a70400a2aac1a1a1f0bc930954e82"

      def install
        bin.install "smallweb"
      end
    end
    on_arm do
      url "https://github.com/pomdtr/smallweb/releases/download/v0.13.1/smallweb_Darwin_arm64.tar.gz"
      sha256 "2f959bebc40a5e17db190c91b5f2543f9af62c8a9275633d3e4edba239ed887e"

      def install
        bin.install "smallweb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pomdtr/smallweb/releases/download/v0.13.1/smallweb_Linux_x86_64.tar.gz"
        sha256 "2e2e1f4053a06edd0c5d0704862ea36729bb04c6e7a316c8dc608b81f58efde8"

        def install
          bin.install "smallweb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pomdtr/smallweb/releases/download/v0.13.1/smallweb_Linux_arm64.tar.gz"
        sha256 "5ddd3c963223bf3b081ec857a1e9659e7449b5f497c55db3364966cd273fbc6f"

        def install
          bin.install "smallweb"
        end
      end
    end
  end
end
