# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smallweb < Formula
  desc ""
  homepage "https://smallweb.run"
  version "0.26.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.26.6/smallweb_Darwin_x86_64.tar.gz"
      sha256 "6ab24ba21418de100d382badf3a98477458d66a286739b83a292d37519f7b9ba"

      def install
        bin.install "smallweb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.26.6/smallweb_Darwin_arm64.tar.gz"
      sha256 "dbcfdfc0a01f73d10f50eeab5d39d45ca211edd1a2ffc6d2ccd1a74049703a0e"

      def install
        bin.install "smallweb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.26.6/smallweb_Linux_x86_64.tar.gz"
      sha256 "b22408c5c388126b56a66f587a760a7b4990a64abac6fb314b5b56f4ab2febb0"
      def install
        bin.install "smallweb"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/smallweb/releases/download/v0.26.6/smallweb_Linux_arm64.tar.gz"
      sha256 "9ad80cbfdc6e929a378a1aa33993d2d949c526799537ed945a0367f98094ae1b"
      def install
        bin.install "smallweb"
      end
    end
  end

  service do
    run [ opt_bin/"smallweb" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/smallweb.log"
    error_log_path var/"log/smallweb.log"
  end
end
