# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sunbeam < Formula
  desc ""
  homepage "https://pomdtr.github.io/sunbeam"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/sunbeam/releases/download/v0.9.3/sunbeam_Darwin_arm64.tar.gz"
      sha256 "ee31ba03da48078ef4549bece83dbbc8ae58b24a65174f86f19da858b9fae9b1"

      def install
        bin.install "sunbeam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/sunbeam/releases/download/v0.9.3/sunbeam_Darwin_x86_64.tar.gz"
      sha256 "f883e63338c9e3657f64b5597e6d40c6bcde0c469e570607bbe12cd87d45daec"

      def install
        bin.install "sunbeam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/sunbeam/releases/download/v0.9.3/sunbeam_Linux_x86_64.tar.gz"
      sha256 "7f5d14a73b5b780a73fe5ea3e5bff2abcce4e3246691dab1b2210703fa2e0d8e"

      def install
        bin.install "sunbeam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/sunbeam/releases/download/v0.9.3/sunbeam_Linux_arm64.tar.gz"
      sha256 "4a0d5ef50a204718ae1728e42653fdbe43cb38c08fca71c19a11a97fe8076c63"

      def install
        bin.install "sunbeam"
      end
    end
  end
end
