# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Survey < Formula
  desc ""
  homepage "https://github.com/pomdtr/survey"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/survey/releases/download/v0.0.1/survey-0.0.1-darwin_amd64.tar.gz"
      sha256 "4e31391fa4b7c2efd16c4ddf122f6b7b169d6f5920487bcf04062e0d2d4ad373"

      def install
        bin.install "survey"
        bash_completion.install "completions/survey.bash"
        zsh_completion.install "completions/survey.zsh"
        fish_completion.install "completions/survey.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/survey/releases/download/v0.0.1/survey-0.0.1-darwin_arm64.tar.gz"
      sha256 "519c0d393ae5bfee5678527bbb7f8b5bc9522807e0ae02b7c8ad3297e8764872"

      def install
        bin.install "survey"
        bash_completion.install "completions/survey.bash"
        zsh_completion.install "completions/survey.zsh"
        fish_completion.install "completions/survey.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/survey/releases/download/v0.0.1/survey-0.0.1-linux_arm64.tar.gz"
      sha256 "b40acfa7c99343abb09eb29f6248be92021d2a6afe1bfea5459ba651da69c5d9"

      def install
        bin.install "survey"
        bash_completion.install "completions/survey.bash"
        zsh_completion.install "completions/survey.zsh"
        fish_completion.install "completions/survey.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/survey/releases/download/v0.0.1/survey-0.0.1-linux_amd64.tar.gz"
      sha256 "17703a3d3975b1f1fde767581ac9fbccc91020f97aba5d3a6f040b1488066f27"

      def install
        bin.install "survey"
        bash_completion.install "completions/survey.bash"
        zsh_completion.install "completions/survey.zsh"
        fish_completion.install "completions/survey.fish"
      end
    end
  end
end
