# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tweety < Formula
  desc ""
  homepage "https://pomdtr.github.io/tweety"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/tweety/releases/download/v0.8.2/tweety-0.8.2-darwin_amd64.tar.gz"
      sha256 "24c8e9d8394976bb808ae10d1e62b61a0c382c42935728e1719edb2a2c0de28c"

      def install
        bin.install "tweety"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/tweety/releases/download/v0.8.2/tweety-0.8.2-darwin_arm64.tar.gz"
      sha256 "01cad3b9e38747f29bff8063a195ad33835ffe10180d78085830f73f557da6b3"

      def install
        bin.install "tweety"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/tweety/releases/download/v0.8.2/tweety-0.8.2-linux_arm64.tar.gz"
      sha256 "9262d41782b56014b1d646e78d99efd856a10c647f38cdb0cc6b6001d1228b84"

      def install
        bin.install "tweety"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/tweety/releases/download/v0.8.2/tweety-0.8.2-linux_amd64.tar.gz"
      sha256 "80683dbed1a4e8a530ea6b9c02bf33dec2a9bb9bbc474338c7c26ca62d1f99e6"

      def install
        bin.install "tweety"
      end
    end
  end

  service do
    run [ opt_bin/"tweety" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/tweety.log"
    error_log_path var/"log/tweety.log"
  end
end
