# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Val < Formula
  desc ""
  homepage "https://github.com/pomdtr/val"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/val/releases/download/v0.0.2/val-0.0.2-darwin_amd64.tar.gz"
      sha256 "0ebca2a70042f4df2f44d032a66392153d5dc3440ee32cd3f57f1160f109afe5"

      def install
        bin.install "val"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/val/releases/download/v0.0.2/val-0.0.2-darwin_arm64.tar.gz"
      sha256 "dc57afcf150c30af06a71b3ae00f4c0ef773b61f1abae75b2045cb595a83fe0e"

      def install
        bin.install "val"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/val/releases/download/v0.0.2/val-0.0.2-linux_amd64.tar.gz"
      sha256 "48182ba7d4ceb0ecaf1d1bd91c305a085f272fe6b7fa72bd763d4c2f2887d701"

      def install
        bin.install "val"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/val/releases/download/v0.0.2/val-0.0.2-linux_arm64.tar.gz"
      sha256 "425c68fa6f501c108f7e882d1dcd98ba428f55f0c64fbc202c9279d964845915"

      def install
        bin.install "val"
      end
    end
  end
end
