# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Val < Formula
  desc ""
  homepage "https://github.com/pomdtr/val"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/val/releases/download/v0.1.0/val-0.1.0-darwin_arm64.tar.gz"
      sha256 "439ee41900aa89b17986567dfac3bee3c3fd0507aa4526d83682ff39f794b0a6"

      def install
        bin.install "val"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/val/releases/download/v0.1.0/val-0.1.0-darwin_amd64.tar.gz"
      sha256 "a41abd19edd497e875fa42484554112a65f03228f9ce8e0acd39589f3fb27f4a"

      def install
        bin.install "val"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/val/releases/download/v0.1.0/val-0.1.0-linux_arm64.tar.gz"
      sha256 "b9d3f45f75d4e5048ecf9de7bf84efe28cf0c815bf1021ee770dc4395be6f09d"

      def install
        bin.install "val"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/val/releases/download/v0.1.0/val-0.1.0-linux_amd64.tar.gz"
      sha256 "e3cf1b43d9c30c039cb7e00541154562f47ce3efe7ed664fd0b24397ff1731e4"

      def install
        bin.install "val"
      end
    end
  end
end
