# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vt < Formula
  desc ""
  homepage "https://github.com/pomdtr/vt"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/vt/releases/download/v0.2.1/vt-0.2.1-darwin_amd64.tar.gz"
      sha256 "81f74137bf2f9d54b645dce80254c3130c24181b90647e259ba8c4aaa6acec2a"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/vt/releases/download/v0.2.1/vt-0.2.1-darwin_arm64.tar.gz"
      sha256 "cd6785601e6ce5ff0ae9d8ccf4da7858e138a69bb68ee362418666fc73d810b5"

      def install
        bin.install "vt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/vt/releases/download/v0.2.1/vt-0.2.1-linux_arm64.tar.gz"
      sha256 "de6992ce5f4ded9d67bb3928ec952fbaed194acb345861bb358c2895e5c9504c"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/vt/releases/download/v0.2.1/vt-0.2.1-linux_amd64.tar.gz"
      sha256 "adfbe9d855afa09f8c3ca29350668692bdabbf3287ee0fa0818b5802a1036dd9"

      def install
        bin.install "vt"
      end
    end
  end
end
