# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vt < Formula
  desc ""
  homepage "https://github.com/pomdtr/vt"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/vt/releases/download/v0.3.0/vt-0.3.0-darwin_arm64.tar.gz"
      sha256 "52590c0191aca67e24a5029fc16df7c8ad8c6d430718cc446fd07fba54965c72"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/vt/releases/download/v0.3.0/vt-0.3.0-darwin_amd64.tar.gz"
      sha256 "82bc4d2619d32c5ae4fa8bf04f624d8ee698a5d3305dc60124740e64011464f1"

      def install
        bin.install "vt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/vt/releases/download/v0.3.0/vt-0.3.0-linux_arm64.tar.gz"
      sha256 "9fc9c71e8c1191d664f3afac24ba1eeda968618db8482735bc94082f4957bc0b"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/vt/releases/download/v0.3.0/vt-0.3.0-linux_amd64.tar.gz"
      sha256 "34bd9e433b99a882d1f0306157bdf9c95cfc044bd2d7f1a923d597cea4e05bc7"

      def install
        bin.install "vt"
      end
    end
  end
end
