# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wesh < Formula
  desc ""
  homepage "https://pomdtr.github.io/wesh"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/wesh/releases/download/v0.1.0/wesh-0.1.0-darwin_amd64.tar.gz"
      sha256 "fd564edbd2841ff8c53a0abd5c1bcfca6ae93cb90635aca3e0e4464afef105e6"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/wesh/releases/download/v0.1.0/wesh-0.1.0-darwin_arm64.tar.gz"
      sha256 "b50b6261f83b6d9ee3d2f0a7c0ac01a9c5fe7d93d550e9d5524108e3f979b1de"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/wesh/releases/download/v0.1.0/wesh-0.1.0-linux_arm64.tar.gz"
      sha256 "03e99892e01a8d683477efca2e9b23f8e27b7a8d8c803181d48eee025ea303de"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/wesh/releases/download/v0.1.0/wesh-0.1.0-linux_amd64.tar.gz"
      sha256 "9240676a350dbb289f76a810471a6402696bd99e90fdccf7a292cfa7b2074812"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
  end
end
