# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wesh < Formula
  desc ""
  homepage "https://pomdtr.github.io/wesh"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/wesh/releases/download/v0.0.1/wesh-0.0.1-darwin_amd64.tar.gz"
      sha256 "16274951fa8d9beacf56ff4c33dfca32cbc0f6fc366a95c284caec2e22df8006"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pomdtr/wesh/releases/download/v0.0.1/wesh-0.0.1-darwin_arm64.tar.gz"
      sha256 "a75cf08196c10bb505237a868fe75c1e393b78bd835982797944e4e6b824f3dd"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomdtr/wesh/releases/download/v0.0.1/wesh-0.0.1-linux_arm64.tar.gz"
      sha256 "c393edf25f984e7642b8f873e1952b61c71fdf678027e2eb1e76f3dd1c2db8db"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomdtr/wesh/releases/download/v0.0.1/wesh-0.0.1-linux_amd64.tar.gz"
      sha256 "ef110a35d0d1d64043e41dc065eee4eb564958311046eda67d6ef7974d408008"

      def install
        bin.install "wesh"
        bash_completion.install "completions/wesh.bash"
        zsh_completion.install "completions/wesh.zsh"
        fish_completion.install "completions/wesh.fish"
      end
    end
  end
end
